name: Update Languages SVG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download generated SVG
        run: |
          curl https://tostesx.github.io/myTopLangs/api -o my_top_langs.svg

      - name: Commit file
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add my_top_langs.svg
          git commit -m "Auto-update language stats SVG" || exit 0
          git push
